version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app.dockerfile
    restart: "no"
    environment:
      - JIRA_USER
      - JIRA_API_TOKEN
      - JIRA_API_URL
      - DEFAULT_TEAM_ID
      - DEFAULT_SIZE
      - STORY_TYPE_ID
      - ORG_ID
      - CF_TEAM
      - CF_EPIC
      - CF_SIZE
      - CF_AC
      - TEMPLATE_FILE
      - SSL_CERT_FILE=/usr/local/share/ca-certificates/zscaler-root-ca.pem 
    volumes:
      - ./app:/app
    command: ./docker-start
